default_install_hook_types:
  - commit-msg
  - pre-commit
  - pre-push
default_stages:
  - pre-commit
  - pre-push
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - post-commit
          - pre-push
