name: reviewdog
on:
  push:
    branches: [main]
  pull_request:
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-yamllint@v1
        with:
          fail_level: error
          filter_mode: nofilter
          reporter: github-pr-check
